[2024-01-08 16:30:23] local.ERROR: Uncaught Symfony\Component\Finder\Exception\DirectoryNotFoundException: The "C:\xampp\htdocs\SE_CAMP\Camp\example-app\resources\views" directory does not exist. in C:\xampp\htdocs\SE_CAMP\example-app\vendor\symfony\finder\Finder.php:649
Stack trace:
#0 C:\xampp\htdocs\SE_CAMP\example-app\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(585): Symfony\Component\Finder\Finder->in('C:\\xampp\\htdocs...')
#1 Command line code(1): Illuminate\Filesystem\Filesystem->files('C:\\xampp\\htdocs...')
#2 Command line code(1): getViews('C:\\xampp\\htdocs...', Object(Illuminate\Filesystem\Filesystem))
#3 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Symfony\\Component\\Finder\\Exception\\DirectoryNotFoundException: The \"C:\\xampp\\htdocs\\SE_CAMP\\Camp\\example-app\\resources\\views\" directory does not exist. in C:\\xampp\\htdocs\\SE_CAMP\\example-app\\vendor\\symfony\\finder\\Finder.php:649
Stack trace:
#0 C:\\xampp\\htdocs\\SE_CAMP\\example-app\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\Filesystem.php(585): Symfony\\Component\\Finder\\Finder->in('C:\\\\xampp\\\\htdocs...')
#1 Command line code(1): Illuminate\\Filesystem\\Filesystem->files('C:\\\\xampp\\\\htdocs...')
#2 Command line code(1): getViews('C:\\\\xampp\\\\htdocs...', Object(Illuminate\\Filesystem\\Filesystem))
#3 {main}
  thrown at C:\\xampp\\htdocs\\SE_CAMP\\example-app\\vendor\\symfony\\finder\\Finder.php:649)
[stacktrace]
#0 {main}
"} 
